### ISSUE TITLE
Clarity on the nature of compression

### ISSUE THREAD

**Issue by krishnakumarg1984** [bnanes/shrink-pdf#3]
Hi,

There is Peter Szabo's [pdfsizeopt](https://github.com/pts/pdfsizeopt) which works by applying various image __lossless__ image compression techniques to the embedded images in the original PDF.

Is `shrink-pdf` lossless? Can you provide some benchmarks/comparisons etc. against `pdfsizeopt`?

**Comment by bnanes** [comment]
No. The PDF Shrinker uses [jpeg compression](https://en.wikipedia.org/wiki/JPEG), which is lossy. Compression is done through the Java ImageI /O API.

**Comment by krishnakumarg1984** [comment]
Thanks for clarifying!
