### ISSUE TITLE
UNIX: Pre-built app line endings and executable bit

### ISSUE THREAD

**Issue by abrac** [bnanes/shrink-pdf#6]
There are two issues with the shrink-pdf.sh file in the [pre-built app archive](https://b.nanes.org/shrink-pdf-beta-5-distr.zip). It needs to have its executable bit set (not sure if this is possible in a zip file), and it needs to have unix line endings (i.e. LF instead of CR). Currently the user needs to make these two changes manually, which can be confusing for non-geeks.

**Comment by bnanes** [comment]
Should be fixed with `beta-6`. Thanks!

**Comment by abrac** [comment]
Additionally, the `javaw` command is deprecated in newer versions of Java.

Thanks so much for this beautiful software! Very handy!
